# Generated by Django 5.2.4 on 2025-07-29 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='township',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.township'),
        ),
    ]
