# Generated by Django 5.2.4 on 2025-07-29 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='isVariant',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='core.product'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', True), ('variant__isnull', False)), models.Q(('product__isnull', False), ('variant__isnull', True)), _connector='OR'), name='inventory_xor_product_variant'),
        ),
    ]
