# Generated by Django 5.2.4 on 2025-07-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_inventory_options_remove_inventory_isvariant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='inventory_xor_product_variant',
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_variant', True), ('variant__isnull', False)), models.Q(('is_variant', False), ('variant__isnull', True)), _connector='OR'), name='inventory_xor_product_variant'),
        ),
    ]
