# Generated by Django 5.2.4 on 2025-07-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cart_total_price_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
