# Generated by Django 5.2.4 on 2025-07-31 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='region',
        ),
    ]
