# Generated by Django 5.2.4 on 2025-07-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='phoneNo',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
