# Generated by Django 5.2.4 on 2025-07-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_paymentmethod_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
