# Generated by Django 5.2.4 on 2025-07-31 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingfee',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, unique=True),
        ),
        migrations.AlterField(
            model_name='shippingfee',
            name='township',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.township', unique=True),
        ),
    ]
